# SELECT *
SELECT A.AUTHOR_ID
     , A.AUTHOR_NAME
     , B.CATEGORY
     , SUM(B.PRICE * S.SALES) AS TOTAL_SALES
  FROM BOOK B
  JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
  JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
 WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;

-- BOOK(판매가), AUTHOR(저자이름), BOOK_SALES(판매량)
-- BOOK <-> AUTHOR
-- BOOK <-> BOOK_SALES
-- 2022년 1월의 저자별 카테고리별 매출액