-- OUTS 기록은 있는데, INS 기록이 없는 동물의 ID와 이름을 ID 순으로 조회
   SELECT O.ANIMAL_ID, O.NAME
     FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I
       ON O.ANIMAL_ID = I.ANIMAL_ID
    WHERE I.ANIMAL_ID IS NULL
 ORDER BY ANIMAL_ID;